# Generated by Django 3.2.7 on 2022-04-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(default='none', max_length=500)),
                ('description', models.CharField(default='none', max_length=50000)),
            ],
        ),
    ]
