# Generated by Django 3.2.7 on 2022-04-17 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_farmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 6, 9, 12, 66070)),
        ),
    ]
