# Generated by Django 3.2.7 on 2022-04-23 07:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0006_auto_20220417_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 1, 45, 40, 11523)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 1, 45, 40, 11523)),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='none', max_length=5000)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 4, 23, 1, 45, 40, 11523))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
