# Generated by Django 3.2.7 on 2022-04-23 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20220423_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 4, 44, 33, 159850)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 4, 44, 33, 159850)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 4, 44, 33, 159850)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 4, 44, 33, 160850)),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.ImageField(default='default.jpg', upload_to='products'),
        ),
    ]
