# Generated by Django 3.2.7 on 2022-04-23 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20220423_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 9, 7, 52, 185816)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='ads'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 9, 7, 52, 184816)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 9, 7, 52, 184816)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 9, 7, 52, 184816)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 9, 7, 52, 185816)),
        ),
    ]
