# Generated by Django 4.0.3 on 2022-04-25 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20220423_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 11, 24, 21, 163804)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 11, 24, 21, 156829)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 11, 24, 21, 158823)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 11, 24, 21, 159821)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 11, 24, 21, 161815)),
        ),
    ]
